const now = new Date();
export const STATUSES = [
  "Lead: Deprioritized Account",
  "Lead: No Current Product Solution",
  "Target Account",
  "Customer Engaged",
  "Proposal Submitted",
  "Win - Customer Verbal",
  "Post-pipeline: Win (order shipped)",
  "Post-pipeline: Loss",
  "Post-pipeline: On-hold",
];

export const STATUS_COLORS = {
  "Lead: Deprioritized Account": "#6B7280",
  "Lead: No Current Product Solution": "#93C5FD",
  "Target Account": "#FCD34D",
  "Customer Engaged": "#39B4E8",
  "Proposal Submitted": "#FB923C",
  "Win - Customer Verbal": "#78BE20",
  "Post-pipeline: Win (order shipped)": "#16A34A",
  "Post-pipeline: Loss": "#C8102E",
  "Post-pipeline: On-hold": "#8B5CF6",
};

export const CHART_COLORS = {
  teal: "#14B8A6",
  purple: "#A78BFA",
  cyan: "#22D3EE",
  grayAxis: "#64748B",
  blue: "#3B82F6",
};

export const BRAND = {
  yellow: "#F6E500",
  blue: "#39B4E8",
  navy: "#00205C",
  deepBlue: "#001489",
  green: "#78BE20",
  red: "#C8102E",
};


export const SALESMAPPING = {
    Bill: "Field Sales",
    Broker: "Broker",
    Canada: "Canada",
    Diana: "Nat'l Account",
    Gregg: "Nat'l Account",
    Jayne: "Field Sales",
    Dan: "Nat'l Account",
    Larry: "Field Sales",
    Meredith: "Field Sales",
    "Michael J": "Field Sales",
    "Mike K": "Field Sales",
    Steve: "Nat'l Account",
    UNKNOWN: "UNKNOWN",
  };


  const OWNERMAPPING = {
    Bill: "bill@doleintl.com",
    Diana: "diana@doleintl.com",
    Gregg: "gregg@doleintl.com",
    Dan: "dan@doleintl.com",
    Steve: "steve@doleintl.com",
  };

  export const OPPORTUNITIES = [
    // Bill's Field Sales opportunities (rows 1-25)
    {
      id: 1,
      title: "&Pizza - Pineapple Juice",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "&Pizza",
      product: "12/46 FL OZ PINEAPPLE JUICE (CONVENIENCE)",
      units2023: 59,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890000818",
      productCategory: "BEVERAGE",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 2,
      title: "bb.q Chicken - Pineapple Juice SW",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "bb.q Chicken",
      product: "2/24/6 OZ PINEAPPLE JUICE SW (CONVENIENCE)",
      units2023: 165,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890000914",
      productCategory: "BEVERAGE",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 3,
      title: "Ben & Jerry's - Pineapple Juice",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Ben & Jerry's",
      product: "8/6/6OZ PINEAPPLE JUICE (CONVENIENCE)",
      units2023: 187,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890000947",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 4,
      title: "Bruegger's - Pineapple Sliced",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Bruegger's",
      product: "12/8 OZ FANCY PINEAPPLE SLICED IN JUICE (CONVENIENCE)",
      units2023: 181,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890001139",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 5,
      title: "Bruster's - Pineapple Chunk",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Bruster's Real Ice Cream",
      product: "12/20 OZ FANCY PINEAPPLE CHUNK JUICE (CONVENIENCE)",
      units2023: 194,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890001473",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 6,
      title: "D'Angelo - Mixed Fruit",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "D'Angelo",
      product: "6/4/4OZ MIXED FRUIT JUICE CUP (CONVENIENCE)",
      units2023: 83,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890003060",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 7,
      title: "Dibella's - Pineapple Chunk",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Dibella's",
      product: "12/8 OZ FANCY PINAPPLE CHUNK IN JUICE (CONVENIENCE)",
      units2023: 43,
      salesStage: "Lead: Deprioritized Account",
      materialId: "3890011469",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 8,
      title: "Duck Donuts - Pineapple Juice",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Duck Donuts",
      product: "12/46 FL OZ PINEAPPLE JUICE (CONVENIENCE)",
      units2023: 125,
      salesStage: "Lead: Deprioritized Account",
      estimatedVolume: 10000,
      materialId: "3890000818",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 9,
      title: "Famous Dave's - Pineapple Juice SW",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Famous Dave's",
      product: "2/24/6 OZ PINEAPPLE JUICE SW (CONVENIENCE)",
      units2023: 116,
      salesStage: "Lead: Deprioritized Account",
      estimatedVolume: 45000,
      materialId: "3890000914",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 10,
      title: "Gino's Pizza - Pineapple Juice",
      amount: 0,
      status: "Lead: Deprioritized Account",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Gino's Pizza & Spaghetti House",
      product: "8/6/6OZ PINEAPPLE JUICE (CONVENIENCE)",
      units2023: 52,
      salesStage: "Lead: Deprioritized Account",
      estimatedVolume: 23400,
      materialId: "3890000947",
      createdAt: new Date(2024, 0, 1),
      closeDate: new Date(2025, 5, 1),
    },

    // Diana's National Account opportunities (rows 26-52)
    {
      id: 26,
      title: "Texas Roadhouse - Pineapple Juice",
      amount: 498261.67,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Texas Roadhouse",
      product: "Pineapple Juice",
      industrySegment: "Casual Dining",
      units2023: 638,
      salesStage: "Customer Engaged",
      estimatedVolume: 15000,
      materialId: "3890011469",
      samplesNeeded: "Y",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2024, 9, 10),
    },
    {
      id: 27,
      title: "Texas Roadhouse - Lemons",
      amount: 127281,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Texas Roadhouse",
      product: "Lemons",
      industrySegment: "Casual Dining",
      units2023: 638,
      salesStage: "Customer Engaged",
      estimatedVolume: 44660,
      materialId: "3890000818",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2024, 9, 10),
    },
    {
      id: 28,
      title: "Twin Peaks - Lemons",
      amount: 1710000,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Twin Peaks",
      product: "Lemons",
      industrySegment: "Casual Dining",
      units2023: 103,
      salesStage: "2. Customer Engaged",
      opportunityType: "New Business",
      estimatedVolume: 20000,
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 2, 20),
    },
    {
      id: 29,
      title: "Wendy's - IQF Lemons",
      amount: 309339,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Wendy's",
      product: "IQF Lemons",
      industrySegment: "QSR",
      units2023: 6030,
      salesStage: "2. Customer Engaged",
      estimatedVolume: 108540,
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 30,
      title: "Wienerschnitzel - Target",
      amount: 0,
      status: "Target Account",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Wienerschnitzel",
      industrySegment: "QSR",
      units2023: 323,
      salesStage: "1. Target Account",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 25),
    },
    {
      id: 31,
      title: "Wingstop - Dole Whip",
      amount: 3000,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Wingstop",
      product: "Dole Whip Pineapple",
      industrySegment: "Fast Casual",
      units2023: 1950,
      salesStage: "2. Customer Engaged",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 5, 1),
    },
    {
      id: 32,
      title: "IHOP - Good Crunch",
      amount: 114720,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "IHOP",
      product: "Good Crunch",
      industrySegment: "Midscale",
      units2023: 1696,
      salesStage: "2. Customer Engaged",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 15),
    },
    {
      id: 33,
      title: "Landry's - 4+1 Strawberries",
      amount: 57176.92,
      status: "Win - Customer Verbal",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Landry's",
      product: "4+1 Strawberries",
      salesStage: "4. Win - Customer Verbal",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 30),
    },
    {
      id: 34,
      title: "Little Caesar - PA Tidbits",
      amount: 105501,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Little Caesar",
      product: "PA Tidbits",
      industrySegment: "QSR",
      salesStage: "2. Customer Engaged",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 9, 1),
    },
    {
      id: 35,
      title: "IHOP - Dragon Fruit",
      amount: 213280,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "IHOP",
      product: "Chef-Ready Cuts Diced Dragon Fruit",
      salesStage: "2. Customer Engaged",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 9, 1),
    },
    {
      id: 36,
      title: "Kahala - IQF Mango",
      amount: 285500,
      status: "Post-pipeline: On-hold",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Kahala (Planet Smoothie)",
      product: "IQF Mango Chunks",
      salesStage: "Post-pipeline: On-hold",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 14),
    },
    {
      id: 38,
      title: "Famous Dave's - Pineapple Crushed",
      amount: 18467.48,
      status: "Proposal Submitted",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Famous Dave's (BBQ Holdings)",
      product: "Pineapple Fancy Crushed",
      salesStage: "Proposal Submitted",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 30),
    },
    {
      id: 42,
      title: "BBQ Holdings - Pineapple Juice VIT SW",
      amount: 1948.8,
      status: "Post-pipeline: Win (order shipped)",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "BBQ Holdings- Barrio Queen",
      product: "pineapple Juice VIT SW",
      salesStage: "Post-pipeline: Win (order shipped)",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 3, 29),
    },
    {
      id: 45,
      title: "Ladle & Leaf - IQF Avocado",
      amount: 17600,
      status: "Post-pipeline: Loss",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Ladle & Leaf",
      product: "IQF Chef-Ready Avocado Diced",
      salesStage: "Post-pipeline: Loss",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 4, 1),
    },
    {
      id: 46,
      title: "Nordstrom - Beverage RFP",
      amount: 30023.47,
      status: "Proposal Submitted",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Nordstrom",
      product: "Beverage RFP ( Pineapple Juice)",
      salesStage: "Proposal Submitted",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 4, 7),
    },
    {
      id: 47,
      title: "Landry's - Strawberry Tub",
      amount: 445980,
      status: "Post-pipeline: Win (order shipped)",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Landry's",
      product: "Strawberry SL 6/6.5# 4+1 Tub",
      salesStage: "Post-pipeline: Win (order shipped)",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 4, 13),
    },
    {
      id: 48,
      title: "Nordstrom - Dole Pineapple juice",
      amount: 30023.47,
      status: "Proposal Submitted",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Nordstrom",
      product: "Dole Pineapple juice",
      salesStage: "Proposal Submitted",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 7, 1),
    },
    {
      id: 49,
      title: "PF Changs - Good Crunch",
      amount: 33200,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "PF Changs",
      product: "Pineapple Good Crunch",
      salesStage: "2. Customer Engaged",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 5, 3),
    },
    {
      id: 50,
      title: "PF Changs - IQF Lemons",
      amount: 205200,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "PF Changs",
      product: "IQF Lemons",
      salesStage: "2. Customer Engaged",
      opportunityType: "New Business",
      createdAt: new Date(2024, 7, 1),
      closeDate: new Date(2025, 5, 3),
    },

    // Add 3 urgent opportunities for testing "Needs Attention"
    {
      id: 100,
      title: "URGENT: Kroger - Review Today",
      amount: 85000,
      status: "Proposal Submitted",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Kroger",
      product: "Mixed Produce",
      salesStage: "Proposal Submitted",
      opportunityType: "New Business",
      createdAt: new Date(
        now.getFullYear(),
        now.getMonth(),
        now.getDate() - 10
      ),
      closeDate: now,
    },
    {
      id: 101,
      title: "URGENT: Walmart - Tomorrow",
      amount: 120000,
      status: "Customer Engaged",
      owner: "diana@doleintl.com",
      doleSalesLead: "Diana",
      salesTeam: "Nat'l Account",
      customerName: "Walmart",
      product: "Fresh Produce",
      salesStage: "2. Customer Engaged",
      opportunityType: "Renewal",
      createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7),
      closeDate: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1),
    },
    {
      id: 102,
      title: "URGENT: Target - 2 Days",
      amount: 95000,
      status: "Customer Engaged",
      owner: "bill@doleintl.com",
      doleSalesLead: "Bill",
      salesTeam: "Field Sales",
      customerName: "Target",
      product: "Juice Products",
      salesStage: "2. Customer Engaged",
      opportunityType: "Expansion",
      createdAt: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5),
      closeDate: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 2),
    },
  ];